prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 30m
        memory: 128Mi
      limits:
        cpu: 150m
        memory: 320Mi
    retention: 12h
    # scrapeInterval: "60s"

grafana:
  resources:
    requests:
      cpu: 30m
      memory: 32Mi
    limits:
      cpu: 150m
      memory: 320Mi

kubeStateMetrics:
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 30m
      memory: 32Mi

nodeExporter:
  resources:
    requests:
      cpu: 5m
      memory: 16Mi
    limits:
      cpu: 20m
      memory: 32Mi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 30m
        memory: 64Mi