apiVersion: v1
kind: Service
metadata:
  name: usuarios-ms
  namespace: proyecto-sa
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: usuarios-ms
  ports:
    - protocol: TCP
      port: 5200
      targetPort: 5200
  type: ClusterIP  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-ms
  namespace: proyecto-sa
  labels:
    app: usuarios-ms
spec:
  selector:
    matchLabels:
      app: usuarios-ms
  template:
    metadata:
      labels:
        app: usuarios-ms
    spec:
      containers:
        - name: usuarios-ms
          image: iskandar1412/proyecto-sa:usuarios
          imagePullPolicy: Always
          ports:
            - containerPort: 5200
          env:
            # CONFIGURACIÓN DB
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DATABASE_PORT
            # CONFIGURACIÓN S3
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: s3-config
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: s3-config
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: s3-config
                  key: AWS_REGION
            - name: AWS_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: s3-config
                  key: AWS_BUCKET_NAME
            # CONFIGURACIÓN CORREO
            - name: BASE_CORREO
              valueFrom:
                configMapKeyRef:
                  name: correo-config
                  key: BASE_CORREO
            - name: BASE_CORREO_PASS
              valueFrom:
                configMapKeyRef:
                  name: correo-config
                  key: BASE_CORREO_PASS
            # CONFIGURACIÓN CORS
            - name: ALLOWED_CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: cors-config
                  key: ALLOWED_CORS_ORIGINS
            # CONFIGURACIÓN JWT
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: JWT_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: JWT_REFRESH_SECRET
            - name: JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: JWT_EXPIRATION
            - name: JWT_REFRESH_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: JWT_REFRESH_EXPIRATION
            # CONFIGURACIÓN AES
            - name: AES_KEY
              valueFrom:
                configMapKeyRef:
                  name: aes-config
                  key: AES_KEY
            - name: AES_IV
              valueFrom:
                configMapKeyRef:
                  name: aes-config
                  key: AES_IV
            # CONFIGURACIÓN USUARIO
            - name: TABLE_USUARIOS
              valueFrom:
                configMapKeyRef:
                  name: usuarios-config
                  key: TABLE_USUARIOS
            # SECRET BASE DE DATOS
            - name: DATABASE_MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DATABASE_MYSQL_USER
            - name: DATABASE_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DATABASE_MYSQL_PASSWORD
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "192m"